"""initial_schema

Revision ID: 1598a0814ee0
Revises: 
Create Date: 2026-09-03 17:29:21.737680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1598a0814ee0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('action_type', sa.Enum('STATE_REPAIR', 'EVENT_REPROCESS', 'PROVIDER_STATUS_QUERY', 'CONTROLLED_REFUND', name='actiontype'), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='actionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_actions_idempotency_key'), 'actions', ['idempotency_key'], unique=True)
    op.create_table('expectations',
    sa.Column('expectation_id', sa.String(), nullable=False),
    sa.Column('refund_intent_id', sa.String(), nullable=False),
    sa.Column('provider_payment_id', sa.String(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sla_seconds', sa.Integer(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('business_reason', sa.String(), nullable=False),
    sa.Column('originating_trace_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('expectation_id')
    )
    op.create_index(op.f('ix_expectations_refund_intent_id'), 'expectations', ['refund_intent_id'], unique=True)
    op.create_table('incidents',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('refund_intent_id', sa.String(), nullable=True),
    sa.Column('lifecycle_state', sa.Enum('OPEN', 'MONITORING', 'ESCALATED', 'RESOLVED', 'CLOSED', name='incidentstate'), nullable=False),
    sa.Column('expectation_id', sa.String(), nullable=True),
    sa.Column('provider_payment_id', sa.String(), nullable=True),
    sa.Column('discrepancy_type', sa.Enum('MATCH', 'IN_FLIGHT_PENDING', 'EPISTEMIC_STALEMATE', 'ABSENT_EXECUTION', 'VALUE_MISMATCH', 'CURRENCY_MISMATCH', 'CONTRADICTORY_TERMINALITY', 'ORPHANED_EXECUTION', 'EXCESS_EFFECT', name='discrepancytype'), nullable=True),
    sa.Column('discrepancy_instance_id', sa.String(), nullable=True),
    sa.Column('discrepancy_history', sa.JSON(), nullable=False),
    sa.Column('reconciliation_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconstructed_state_ids', sa.JSON(), nullable=False),
    sa.Column('evidence_references', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('next_evaluation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monitoring_reason', sa.String(), nullable=True),
    sa.Column('query_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_index(op.f('ix_incidents_refund_intent_id'), 'incidents', ['refund_intent_id'], unique=True)
    op.create_table('observations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_entity_id'), 'observations', ['entity_id'], unique=False)
    op.create_index(op.f('ix_observations_event_id'), 'observations', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observations_event_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_entity_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_incidents_refund_intent_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_expectations_refund_intent_id'), table_name='expectations')
    op.drop_table('expectations')
    op.drop_index(op.f('ix_actions_idempotency_key'), table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###
