"""Add ingestion payloads

Revision ID: 51b68ed33763
Revises: 5dfb76dae033
Create Date: 2026-09-04 14:07:14.251960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51b68ed33763'
down_revision: Union[str, Sequence[str], None] = '5dfb76dae033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('substrate_ingestion_payloads',
    sa.Column('payload_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', 'DUPLICATE', name='payloadprocessingstatus'), nullable=False),
    sa.Column('lease_owner', sa.String(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('payload_id'),
    sa.UniqueConstraint('provider', 'idempotency_key', name='uq_ingestion_provider_idempotency')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('substrate_ingestion_payloads')
    # ### end Alembic commands ###
