"""Add V2 schemas and leased_at

Revision ID: 8a848f4e7966
Revises: 1598a0814ee0
Create Date: 2026-09-03 18:19:25.561944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a848f4e7966'
down_revision: Union[str, Sequence[str], None] = '1598a0814ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v2_active_incidents',
    sa.Column('active_subject', sa.String(), nullable=False),
    sa.Column('discrepancy_reason', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'INVESTIGATING', 'VERIFYING', 'RETRY_PENDING', 'ESCALATED', 'COMPLETED', name='investigationstate'), nullable=False),
    sa.Column('lease_owner', sa.String(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hypothesis_payload', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('active_subject', 'discrepancy_reason'),
    sa.UniqueConstraint('incident_id')
    )
    op.create_table('v2_control_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.Enum('OBSERVATION_INGESTED', 'DISCREPANCY_DETECTED', 'VERIFICATION_SUCCEEDED', name='controleventtype'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('leased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('v2_evidence',
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('raw_payload_ref', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_table('v2_expectations',
    sa.Column('expectation_id', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('expected_state', sa.String(), nullable=False),
    sa.Column('expected_amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('business_status', sa.Enum('CREATED', 'OPEN', 'SATISFIED', 'FAILED', 'EXPIRED', name='businessstatus'), nullable=False),
    sa.Column('correlation_keys', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('expectation_id')
    )
    op.create_table('v2_observations',
    sa.Column('observation_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_reference', sa.String(), nullable=False),
    sa.Column('observation_type', sa.String(), nullable=False),
    sa.Column('observed_state', sa.String(), nullable=False),
    sa.Column('observed_amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('correlation_keys', sa.JSON(), nullable=False),
    sa.Column('provider_event_id', sa.String(), nullable=True),
    sa.Column('provider_version', sa.String(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingestion_event_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('observation_id'),
    sa.UniqueConstraint('ingestion_event_id'),
    sa.UniqueConstraint('provider', 'provider_reference', 'observation_type', 'provider_event_id', name='uq_obs_instance_event'),
    sa.UniqueConstraint('provider', 'provider_reference', 'observation_type', 'provider_version', name='uq_obs_instance_version')
    )
    op.create_table('v2_reconciliation_results',
    sa.Column('reconciliation_id', sa.String(), nullable=False),
    sa.Column('expectation_id', sa.String(), nullable=True),
    sa.Column('observation_ids', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.Enum('MATCH', 'DISCREPANCY', name='reconciliationoutcome'), nullable=False),
    sa.Column('reconciliation_reason', sa.String(), nullable=False),
    sa.Column('discrepancy_reason', sa.Enum('ABSENT_EXECUTION', 'AMOUNT_MISMATCH', 'STATE_MISMATCH', 'DUPLICATE_EXECUTION', 'UNEXPECTED_EXECUTION', 'SLA_BREACH', name='discrepancyreason'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('reconciliation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('v2_reconciliation_results')
    op.drop_table('v2_observations')
    op.drop_table('v2_expectations')
    op.drop_table('v2_evidence')
    op.drop_table('v2_control_events')
    op.drop_table('v2_active_incidents')
    # ### end Alembic commands ###
