"""Add Governance models

Revision ID: a23d7d9dfb7e
Revises: 8a848f4e7966
Create Date: 2026-09-04 10:29:53.635707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a23d7d9dfb7e'
down_revision: Union[str, Sequence[str], None] = '8a848f4e7966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v2_action_budgets',
    sa.Column('budget_id', sa.String(), nullable=False),
    sa.Column('target_action', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('count_limit', sa.Integer(), nullable=False),
    sa.Column('monetary_limit', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('count_used', sa.Integer(), nullable=False),
    sa.Column('monetary_used', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('budget_id')
    )
    op.create_index(op.f('ix_v2_action_budgets_target_action'), 'v2_action_budgets', ['target_action'], unique=False)
    op.create_table('v2_actuation_records',
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('execution_identity', sa.String(), nullable=False),
    sa.Column('intent_action', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('mutation_parameters_canonical', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_actuation_identity_action', 'v2_actuation_records', ['execution_identity', 'intent_action'], unique=False)
    op.create_index(op.f('ix_v2_actuation_records_execution_identity'), 'v2_actuation_records', ['execution_identity'], unique=False)
    op.create_table('v2_control_plane_state',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('automation_state', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('v2_operator_actions',
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('resulting_intent_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_v2_operator_actions_incident_id'), 'v2_operator_actions', ['incident_id'], unique=False)

    op.add_column('v2_active_incidents', sa.Column('version', sa.Integer(), nullable=False))
    op.alter_column('v2_active_incidents', 'state',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.Enum('ACTIVE', 'INVESTIGATING', 'VERIFYING', 'ACTUATION_PENDING', 'RETRY_PENDING', 'ESCALATED', 'COMPLETED', name='investigationstate'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('v2_active_incidents', 'state',
               existing_type=sa.Enum('ACTIVE', 'INVESTIGATING', 'VERIFYING', 'ACTUATION_PENDING', 'RETRY_PENDING', 'ESCALATED', 'COMPLETED', name='investigationstate'),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)
    op.drop_column('v2_active_incidents', 'version')
    op.create_table('evidence',
    sa.Column('evidence_id', sa.TEXT(), nullable=True),
    sa.Column('source', sa.TEXT(), nullable=False),
    sa.Column('entity_id', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.TEXT(), nullable=False),
    sa.Column('evidence_type', sa.TEXT(), nullable=False),
    sa.Column('payload', sa.TEXT(), nullable=False),
    sa.Column('provenance', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('idx_evidence_source_entity'), 'evidence', ['source', 'entity_id'], unique=False)
    op.drop_index(op.f('ix_v2_operator_actions_incident_id'), table_name='v2_operator_actions')
    op.drop_table('v2_operator_actions')
    op.drop_table('v2_control_plane_state')
    op.drop_index(op.f('ix_v2_actuation_records_execution_identity'), table_name='v2_actuation_records')
    op.drop_index('idx_actuation_identity_action', table_name='v2_actuation_records')
    op.drop_table('v2_actuation_records')
    op.drop_index(op.f('ix_v2_action_budgets_target_action'), table_name='v2_action_budgets')
    op.drop_table('v2_action_budgets')
    # ### end Alembic commands ###
