"""Add leased_at to v2_control_events

Revision ID: ce21d1b78f57
Revises: 1598a0814ee0
Create Date: 2026-09-03 18:02:24.063469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce21d1b78f57'
down_revision: Union[str, Sequence[str], None] = '1598a0814ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('v2_control_events', sa.Column('leased_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('v2_control_events', 'leased_at')
    # ### end Alembic commands ###
